// <auto-generated />
namespace MoveGames.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class initials1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initials1));
        
        string IMigrationMetadata.Id
        {
            get { return "201808161454396_initials1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
